config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :events
root 'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :event

  validates :email, presence: true
  validates :event_id, presence: true

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  validates :email, uniqueness: { scope: :event_id }

end

app/models/event.rb
class Event < ApplicationRecord
has_many :checkins, dependent: :destroy
validates :event_name, presence: true
validates :event_datetime, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'You have been checked in!' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
	      format.html { redirect_to @checkin, notice: 'Email has been successfully edited.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
	    format.html { redirect_to @checkin.event, notice: 'You have been checked out!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:email, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
	  @event = Event.find(params[:id])
	  @checkins = @event.checkins
 
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully canceled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/checkins/_form.html.erb
<%= form_with(model: checkin, local: true) do |form| %>
  <% if checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select(:event_id, Event.all, :id, :event_name, :include_blank => true) %>
    <!--
	    <%= form.text_field :event_name %>
    -->

  </div>

  <div class="actions">
    <%= form.submit "Check in"%>
  </div>
<% end %>

app/views/checkins/_form2.html.erb
<%= form_with(model: checkin, local: true) do |form| %>
  <% if checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
<!--
  <div class="field">
    <%= form.label :event_id %>
    <%= form.collection_select(:event_id, Event.all, :id, :event_name, :include_blank => true) %>
    </div>
  -->
  <div class="actions">
    <%= form.submit "Save new email" %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Changing Email</h1>

<%= render 'form2', checkin: @checkin %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', @checkin.event %>

app/views/checkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.email %></td>
        <td><%= checkin.event %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>Check in to an Event</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Back', events_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @checkin.email %>
</p>

<p>
  <strong>Event:</strong>
  <%= @checkin.event.event_name %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', @checkin.event %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Event Name" %>
    <%= form.text_field :event_name %>
  </div>

  <div class="field">
    <%= form.label "Date & Time" %>
    <%= form.datetime_select :event_datetime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Manager</h1>

<% if @events.any? %>
	<br>
	<h2>List of Events</h2>

<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date & Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_datetime %></td>
        <td><%= link_to 'Attendees', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Cancel', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
	<h3> There are no events!</h3>

<% end %>

<br>

<%= link_to 'New Event', new_event_path %>
<br>

<% if @events.any? %>
<%= link_to 'Check in to Event', new_checkin_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Date & Time:</strong>
  <%= @event.event_datetime %>
</p>

<div class="col-md-8">
    <% if @event.checkins.any? %>
      <h3>Attendees (<%= @event.checkins.count %>)</h3>

        <table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Check In Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.email %></td>
        <td><%= checkin.created_at %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Check Out', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
	</table>

<% else %>
	<h3> There are no attendees checked in!</h3>
      
    <% end %>
  </div>




<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>